### ISSUE TITLE
class `MetadataStream::VideoSegment` is not documented.

### ISSUE THREAD

**Issue by anna-khakimova** [apavlenko/vmf#43]
class `MetadataStream::VideoSegment` and `convertTimestampToFrameIndex ()`, `convertFrameIndexToTimestamp ()`  methods of `MetadataStream` class are not documented.

**Comment by anna-plyakina** [comment]
class MetadataStream::VideoSegment, convertTimestampToFrameIndex (), convertFrameIndexToTimestamp ()  were not documented.

**Comment by apavlenko** [comment]
fixed in #42
